### ISSUE TITLE
Getting "Loading..."

### ISSUE THREAD

**Issue by Fastidious** [dtonon/oracolo#2]
Used the "I hate NPM" method, and I see my information at the top, but the posts do not load (just get the "Loading..." message). What could it be?

**Comment by dtonon** [comment]
Weird, can you share the top lines of the html file?

**Comment by Fastidious** [comment]
Found the issue. Cisco Umbrella is blocking the  relays. I will have to wait for the 24 hours penalty for them to become available. Sorry for the noise, and thanks!

**Comment by Fastidious** [comment]
Follow up on this. For Oracolo to work, the notes need to be `kind:30023`. If there aren't any of that kind, it will not work.

**Comment by dtonon** [comment]
Yes, I confirm. Oracolo is a blog and so currently it only uses the long format. The short format could be integrate but it has a lot of pitfalls in this context, for example it doesn't have a title, end often short notes are not so meaningful, so they should be filtered (by lenght? tags? idk).

I already have a working version, where I use the date as title:

<img width="964" alt="image" src="https://github.com/dtonon/oracolo/assets/89577423/4727b4dd-0d9b-4a82-8d32-e2cab3fb8372">

But I don't like it very much.
I need to think more about this uses case.

**Comment by Fastidious** [comment]
Do you have that version publicly available somewhere? I would love to play with it! :-)

**Comment by dtonon** [comment]
https://github.com/dtonon/oracolo/tree/short-notes
