### ISSUE TITLE
Support short notes in the main feed

### ISSUE THREAD

**Issue by jooray** [dtonon/oracolo#9]
Hey,

  I am trying it out, displaying also short notes min 3 characters and no comments. I get the correct profile image and profile description, so some communication with Nostr relays is going well. I also see in developer tools when I look at the websocket connections, that the relays returned some posts, but I never get any content displayed, the circle is turning, but nothing is displayed besides profile info.

   Developer Console does not return any errors.

   Configuration:

```html
 
    <!-- Configure with your npub/nprofile -->
    <meta name="author" value="npub13hwewnhm52g4wpwuvjczwj82e0gk9vc4gprm0efj6l4n678c2f8qt7eaev" />

    <!-- Personalize your relays list -->
    <meta name="relays" value="wss://nos.lol, wss://relay.damus.io, wss://relay.nostr.band, wss://nostr.wine" />

    <!-- Show top notes with images, use a even value, zero to disable -->
    <meta name="top-notes" value="0" />

    <!-- Enable short notes with X minimum characters, zero to disable -->
    <meta name="short-chars" value="3" />

    <!-- Enable navigation by topics (tags), empty to disable -->
    <meta name="topics" value="" />

    <!-- Enable comments, 'yes' to enable -->
    <meta name="comments" value="no" />

```

    Any hints?

**Comment by dtonon** [comment]
Do you have at least one long format post?
If so, can you share the naddr, please?

**Comment by jooray** [comment]
No, only short form posts, maybe that is the problem.

I am experimenting with making Oracolo one of the front-ends for my project [anonmicroblog](https://github.com/jooray/anonmicroblog), but there it's all short form without titles or images.

**Comment by dtonon** [comment]
I suppose this is the problem, Oracolo is designed to handle the long format.
I will evaluate if add an option to use all the notes.

**Comment by jooray** [comment]
I wrote something similar as oracolo for short posts. I'll share GitHub link in the next few days, I have to polish it a bit.

**Comment by dtonon** [comment]
This experimental version support the kind:1 in the main feed:
https://github.com/dtonon/oracolo/tree/short-notes-feed

**Comment by jooray** [comment]
Amazing! Works beautiful.

A few suggestions - since it is short notes, it should be possible to display whole notes without clicking. It is often cut mid sentence, but there's not much to it, it would work better with just full short notes.

And it does not display images in the short notes.

But for me it's good enough already.

**Comment by dtonon** [comment]
> display whole notes without clicking.

This is where things start to get tricky, because the note may include media.
Btw, I (forced) pushed an update that support that using the `short-feed-summary` meta to customize the length (zero for the full display). In this case the style are slightly optimized for the full notes.

> And it does not display images in the short notes.

Fixed.

**Comment by jooray** [comment]
It's perfect.

I commited also [my minimalistic take on short note viewer](https://github.com/jooray/anonmicroblog/tree/main/webview), but now oracolo is better. I had a specific goal in mind, so someone might find my tool useful for finetuning, it is really small code (around 4KB of code, around 56KB compiled).
